spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: thejaspk2020@gmail.com
    password: your-app-password   # use App Password (not your Gmail login password)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: dGhlMjU2Yml0U2VjcmV0S2V5Rm9ySGFzaDI1NlRva2Vucw== 
  expiration-ms: 3600000 
