spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: mysecretkey1234567890
  expiration-ms: 3600000
